### PR TITLE
🐛 Ensure TOC operations are in correct context

### PR DESCRIPTION
**Pull request by Lemmingh**
## Summary

* Hoist the calls to `loadTocConfig()` to the four entrances that needs it.
* `loadTocConfig(editor: vscode.TextEditor): void`.
* Remove `getText()`, which was introduced in d9bce775fefe92b2b74f8462469edde81f61d3ba, and is no longer needed. (And it was indeed a bad design.)
* Limit the retrieval of `TextEditor` to the five entrances. Remove other calls.
* Resolve compiler warnings.

I'm honestly not satisfied with this solution, although I it works. Ideally, there should be a centralized event-driven configuration cache. Then, we won't call `loadTocConfig()`, but request config by document URI. However, it seems complex, and I have another big bug to fix.

## Background

The old implementation may read wrong `TextEditor`, or even `undefined`. We've received a lot of reports, mainly:

* When switching editor layout blazingly fast.
* When focusing the preview.

## Verification steps

1. **View** > **Editor Layout** > **Two Columns**.
2. Put a Markdown document with TOC in one column.
3. Put a non-text editor view, eg. the Welcome page, in another column.
4. Open **Developer Tools Console**.
5. Focus the non-text editor view.
6. **Reload Window**.

### Expected behavior (fix)

* **No** error message.
* The code lens for TOC **appears**.

### The old behavior (bug)

* Get **error** message, typically:

  ```
  ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at loadTocConfig
    at generateTocText
    at detectTocRanges
    at TocCodeLensProvider.provideCodeLenses
  ```

* The code lens for TOC does **not** appear.

### CODE REVIEW

File: src/toc.ts [hunk 1]
```diff
@@ -2,9 +2,19 @@
 
 import * as path from 'path';
 import * as stringSimilarity from 'string-similarity';
+import * as vscode from 'vscode';
```
Comment (yzhang-gh) [inline src/toc.ts:5]: This looks unnecessary. With the following line, we can save a lot of space for `vscode.`

File: src/toc.ts [hunk 2]
```diff
@@ -23,12 +33,14 @@ export function activate(context: ExtensionContext) {
 }
 
 async function createToc() {
-    let editor = window.activeTextEditor;
+    const editor = vscode.window.activeTextEditor;
```
Comment (yzhang-gh) [inline src/toc.ts:36]: e.g., here.

File: src/toc.ts [hunk 3]
```diff
@@ -23,12 +33,14 @@ export function activate(context: ExtensionContext) {
...
 
-    if (!isMdEditor(editor)) {
+    if (!(editor && isMdEditor(editor))) {
```
Comment (yzhang-gh) [inline src/toc.ts:38]: `isMdEditor` will do the null check. I think it is reasonable (`null` is not a Markdown editor of course) and is also quite handy (don't need to manually check it every time).

File: src/toc.ts [hunk 4]
```diff
@@ -51,7 +65,7 @@ async function updateToc() {
     await editor.edit(editBuilder => {
         for (const tocRange of tocRanges) {
             if (tocRange !== null) {
-                const oldToc = getText(tocRange).replace(/\r?\n|\r/g, docConfig.eol);
+                const oldToc = doc.getText(tocRange).replace(/\r?\n|\r/g, docConfig.eol);
```
Comment (yzhang-gh) [inline src/toc.ts:68]: 👍

File: src/toc.ts [hunk 5]
```diff
@@ -126,8 +142,8 @@ function normalizePath(path: string): string {
 }
 
 //// Returns a list of user defined excluded headings for the given document.
-function getExcludedHeadings(doc: TextDocument): { level: number, text: string }[] {
-    const configObj = workspace.getConfiguration('markdown.extension.toc').get<object>('omittedFromToc');
+function getExcludedHeadings(doc: vscode.TextDocument): { level: number, text: string; }[] {
+    const configObj = vscode.workspace.getConfiguration('markdown.extension.toc').get<{ [path: string]: string[]; }>('omittedFromToc');
```
Comment (yzhang-gh) [inline src/toc.ts:146]: `vscode.`

File: src/toc.ts [hunk 6]
```diff
@@ -305,21 +320,25 @@ function onWillSave(e: TextDocumentWillSaveEvent) {
...
         tocConfig.endDepth = Number(matches[2]);
     }
-    tocConfig.orderedList = tocSectionCfg.get<boolean>('orderedList');
-    tocConfig.listMarker = tocSectionCfg.get<string>('unorderedList.marker');
-    tocConfig.plaintext = tocSectionCfg.get<boolean>('plaintext');
-    tocConfig.updateOnSave = tocSectionCfg.get<boolean>('updateOnSave');
+    tocConfig.orderedList = tocSectionCfg.get<boolean>('orderedList')!;
+    tocConfig.listMarker = tocSectionCfg.get<string>('unorderedList.marker')!;
+    tocConfig.plaintext = tocSectionCfg.get<boolean>('plaintext')!;
+    tocConfig.updateOnSave = tocSectionCfg.get<boolean>('updateOnSave')!;
```
Comment (yzhang-gh) [inline src/toc.ts:338]: I think it is okay to use `!` to suppress the compiler warnings. But maybe we can use `get(key, defaultValue)`?

File: src/toc.ts [hunk 7]
```diff
@@ -305,21 +320,25 @@ function onWillSave(e: TextDocumentWillSaveEvent) {
...
 
     // Load workspace config
-    let activeEditor = window.activeTextEditor;
+    const activeEditor = editor;
```
Comment (yzhang-gh) [inline src/toc.ts:341]: Looks like we don't need to claim `activeEditor` at all

File: src/toc.ts [hunk 8]
```diff
@@ -196,7 +196,7 @@ async function generateTocText(doc: TextDocument): Promise<string> {
     const startDepth = Math.max(tocConfig.startDepth, Math.min(...tocEntries.map(h => h.level)));
     let order = new Array(tocConfig.endDepth - startDepth + 1).fill(0); // Used for ordered list
 
-    const anchorOccurances: { [slug: string]: number; } = {};
+    const anchorOccurrences: { [slug: string]: number; } = {};
```
Comment (yzhang-gh) [inline src/toc.ts:199]: 🤣

**Review by yzhang-gh — COMMENTED** [review]
Thanks for the essential changes.

As you may notice, some of the code dates back to 2017 when there aren't Welcome pages or webview recovery (on reload). Actually I never realized this (partially because I didn't remember there have been explicit issue reports on this?).

Anyway, good catch!

File: src/toc.ts (hunk 1 above)
Comment (Lemmingh) [reply src/toc.ts:5]: Recommended practice:

[**Use the namespace import pattern if you’re importing a large number of things.**](https://www.typescriptlang.org/docs/handbook/modules.html#use-the-namespace-import-pattern-if-youre-importing-a-large-number-of-things)

---

From my experience, when probably or already importing more than **five** items, the namespace import is convenient.

Of course, when reading commit history, I noticed you're hesitant about it.

File: src/toc.ts (hunk 6 above)
Comment (Lemmingh) [reply src/toc.ts:338]: But that may increase **maintenance burden**:

If we decide to change the default value of a setting someday, we'll have to search the whole codebase.

---

I prefer to establish a **convention:**

Always set default value in `package.json`.

**Comment by Lemmingh** [comment]
> 2017 when there aren't Welcome pages or webview recovery (on reload).

I fist encountered the bug when in Extension Development Host, I opened a Markdown document and a Settings page, then pressed `Ctrl+Alt+Right` and `Ctrl+Alt+Left` quickly. 😂

> I didn't remember there have been explicit issue reports on this?

No explicit report. But similar messages appeared in a few different discussions.

File: src/toc.ts (hunk 3 above)
Comment (Lemmingh) [reply src/toc.ts:38]: IMHO, a function is a **black box** to the caller.

The return value of `(editor): boolean` is `true` does **not** mean `editor` is not null.

File: src/toc.ts (hunk 1 above)
Comment (yzhang-gh) [reply src/toc.ts:5]: > Of course, when reading commit history, I noticed you're hesitant about it.

I gradually came to the current preference (saving space as the main criterion, it also improves clarity). You can easily get a very long function header if we keep all the `vscode.` (especially for some VS Code APIs). So in contrast, I prefer to use `vscode.`  if there are not many `vscode.` accesses in that file. (I remember there was a commit where I removed many `vscode.`.)

> Recommended practice:
>
> Use the namespace import pattern if you’re importing a large number of things.

It looks more like a thing that should be done on the VS Code API side. IMO, it is better to have ONE long line in the beginning than having to repeat `vscode.` many times everywhere.

File: src/toc.ts (hunk 6 above)
Comment (yzhang-gh) [reply src/toc.ts:338]: Then let's go for `!` 👌

File: src/toc.ts (hunk 3 above)
Comment (yzhang-gh) [reply src/toc.ts:38]: I don't quite understand 😳.

`isMdEditor` returns `true` only when it is a Markdown editor (allowing `null` as input).

https://github.com/yzhang-gh/vscode-markdown/blob/eff0d51e5c271c9fafaa3dfff144cc7c7ae4e7da/src/util.ts#L16-L18

Comment (Lemmingh) [reply src/toc.ts:38]: I mean, you cannot prove such inference:

> Let,
>
> * `e` be a `nullable` object.
> * `f` be a `(p: object) => boolean` function.
>
> If,
>
> * `f(e)` is `true`.
>
> Then,
>
> * `e` is not `null`.

---

See, in C#, we write a lot of

```csharp
if (paramA == null)
{
    throw new ArgumentNullException(nameof(paramA));
}
```

C# is a language, which requires **strict static type checks**.

**TypeScript is a language, which adds such checks to JavaScript.**

I believe we should adhere to the type system.

File: src/toc.ts (hunk 1 above)
Comment (Lemmingh) [reply src/toc.ts:5]: > I remember there was a commit where I removed many `vscode`.

You actually added and removed it many many times.

---

> It looks more like a thing that should be done on the VS Code API side.

?

This advice is about `import`. It is for **consumers** (people like us), not module creators.

---

> IMO, it is better to have ONE long line in the beginning

Preference again ... 😅

* I don't consider line length as a problem. In Android development, we write much longer.
* In .NET, I only do `using Namespace` for `System` plus a few well-known namespaces in the framework. For other cases, either `using alias = Namespace`, or fully qualified name. That makes me feel safe.
* From my experience, code completion is more handy with fully qualified name. TAB TAB TAB, done. Very fast, only very few candidates.

Comment (yzhang-gh) [reply src/toc.ts:5]: > You actually added and removed it many many times.

Finally, I settled down with the current preference 😏.

> This advice is about `import`. It is for consumers (people like us), not module creators.

Alright, I misread that. It is probably good for engineering, but I still keep my personal taste (see below).

> Preference again ... 😅

Of course it is preference. And your text explained a lot about the preference diff. Java and C# are known to be "heavy"/"tedious" (esp. Java 😂). And my main working language is Python... Although I do not like many aspects of it (e.g. indentation), I have to admit its conciseness is a relief.

In the case, I'm okay with both (I have no intention to 100% align with the recommended practices), as long as we don't add `vscode.` back to some lines like this

https://github.com/yzhang-gh/vscode-markdown/blob/347059896d4b779c8d9459970f5ca07db1dfb043/src/util.ts#L23

(Three `vscode.` in a line, I cannot take it.)

File: src/toc.ts (hunk 3 above)
Comment (yzhang-gh) [reply src/toc.ts:38]: Why do I need to think of any possible `f` 😳? Here we know (in our implementation) if `isMdEditor(e)` is `true`, then `e` is not `null`. And it is logically sound from the name.

Comment (Lemmingh) [reply src/toc.ts:38]: **strict static type checks**

Compiler does not care about the meaning of the function name. And here is no easy way to tell you intention to it.

Comment (yzhang-gh) [reply src/toc.ts:38]: I get it now. (Again, I am so used to dynamic programming languages and didn't have the context. It could have been better if you reminded me in the beginning that we(/you) are adding strict type check. 😓)

File: src/toc.ts (hunk 1 above)
Comment (Lemmingh) [reply src/toc.ts]: OK. Rolled back to named import in `toc.ts`.

But I'll still do it my way in **new** modules.

**Review by yzhang-gh — APPROVED** [review]
LGTM. Cheers
